### ISSUE TITLE
DNS provider causing intermittent timeouts 

### ISSUE THREAD

**Issue by blouisdiddy** [Curacubby/issue-status#15]
Our Upstream Network DNS provider is experiencing issues and consequently making it difficult for users to access curacubby controlled sites (portals,attendance kiosk,etc).
At this time there is intermittent connectivity based upon their up and down outage. We are in the process of moving all Sites to available online resources. 
We will update this on a 30-minute cadence.

--------------------------------------------------------------

Upstream engineers found the issue started at 17:54 UTC Aug 23rd, and are in communication with the DNS provider and are currently working to fix the issue.
-------------------------------------------------------------

### All sites are up but we are monitoring closely over the next hours. This issue is pending still while we monitor.
---------------------------------------------

This issue has been resolved.  Our hosting and network DNS provider have closed the issue on their side

**Comment by AdrianArtiles** [comment]
Upstream engineers found the issue started at 17:54 UTC Aug 23rd, and are in communication with the DNS provider and are currently working to fix the issue.
